openapi: 3.0.3
info:
  title: The Collectors Press APIs
  version: 1.0.0
paths:
  /home:
    get:
      summary: Home Route
      responses:
        "200":
          description: OK

  /account:
    get:
      summary: Account Route
      responses:
        "200":
          description: OK

  /account/subscription:
    get:
      summary: Account Subscription Route
      responses:
        "200":
          description: OK

  /account/subscription/cancel:
    post:
      summary: Account Subscription Cancel Route
      responses:
        "204":
          description: No Content

  /account/subscription/renew:
    post:
      summary: Account Subscription Renew
      responses:
        "200":
          description: OK

  /account/help:
    get:
      summary: Account Help
      responses:
        "200":
          description: OK

  /articles/{article_id}:
    get:
      summary: Get Article by ID
      parameters:
        - name: article_id
          in: path
          required: true
          schema:
            type: string
            description: ID of the article

      responses:
        "200":
          description: OK

  /signup:
    post:
      summary: Sign Up
      responses:
        "200":
          description: OK

  /login:
    post:
      summary: Log In
      responses:
        "200":
          description: OK

  /categories/all:
    get:
      summary: All Categories
      responses:
        "200":
          description: OK

  /categories/{category_id}:
    get:
      summary: Get Category by ID
      parameters:
        - name: category_id
          in: path
          required: true
          schema:
            type: string
            description: ID of the Category

      responses:
        "200":
          description: OK

  /dashboard:
    get:
      summary: Dashboard
      responses:
        "200":
          description: OK

  /dashboard/articles:
    get:
      summary: Dashboard Articles
      responses:
        "200":
          description: OK

  /dashboard/articles/{status}:
    get:
      summary: Dashboard articles filtered by status
      parameters:
        - name: status
          in: path
          required: true
          schema:
            type: string
            description: Statuses of article

      responses:
        "200":
          description: OK

  /dashboard/preview_article:
    get:
      summary: Article preview
      responses:
        "200":
          description: OK

  /dashboard/create_article:
    post:
      summary: Article preview
      responses:
        "200":
          description: OK

  /dashboard/publish_article:
    post:
      summary: Publish article
      responses:
        "200":
          description: OK

  /dashboard/delete_article:
    post:
      summary: Delete article
      responses:
        "204":
          description: No Content

  /search:
    get:
      summary: Search all or with query
      parameters:
        - name: query
          in: query
          required: false
          schema:
            type: string
          description: Search query
      responses:
        "200":
          description: OK

  /search/{query}:
    get:
      summary: Search by path query
      parameters:
        - name: query
          in: path
          required: true
          schema:
            type: string
      responses:
        "200":
          description: OK

  /search/category/{id}:
    get:
      summary: Search by category
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string

        - name: query
          in: query
          required: false
          schema:
            type: string
          description: Optional search query within category

    responses:
      "200":
        description: OK

  /search/category/{id}/{query}:
    get:
      summary: Search by category and query (path style)
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string

        - name: query
          in: path
          required: true
          schema:
            type: string

      responses:
        "200":
          description: OK

  /subscription:
    get:
      summary: Subscriptions page
      responses:
        "200":
          description: OK

  /subscription/learn:
    get:
      summary: Subscription payment
      responses:
        "200":
          description: OK

  /subscription/payment:
    post:
      summary: Subscription payment
      responses:
        "200":
          description: OK
